"use client";
import Signin from "@/Components/Account/Signin";


export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};


function SigninPage() {
	return <section><Signin /></section>;
}

export default SigninPage;
