import AboutUs from "@/Components/About/AboutUs";
import Head from "next/head";


export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};


export default function About() {
	return (
		<>
			{/* <Head>
				<link
					rel="shortcut icon"
					type="image/x-icon"
					href="assets/img/favicon.png"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>

				<meta name="description" content="Divita Watch Blogs" />
				<title>Blogs - Divita Watch</title>
			</Head> */}
			<AboutUs />
		</>
	);
}
