"use client"
import Register from "@/Components/Account/Register";


export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};


export default function RegisterPage() {
	return (
		<section>
			<Register />
		</section>
	);
}
