"use client";

import { CacheProvider } from "@emotion/react";

import "../styles/globals.css";
import "../styles/home.css";
// import { Inter } from "next/font/google";

import Footer from "@/Components/Footer";
import createEmotionCache from "@/utility/createEmotionCache";
import { SnackbarProvider } from "notistack";
import Header from "@/Components/Header/Header";
import ScrollToTopBtn from "@/Components/Helpers/ScrollToTopBtn";
import { StoreProvider } from "@/context/Store";

// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

const RootLayout = ({ children }) => {
	// const cache = createEmotionCache();

	return (
		<html lang="en" className="no-touch">
			<head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</head>
			{/* <CacheProvider value={cache}> */}
				<body>
					<StoreProvider>
						<SnackbarProvider
							maxSnack={3}
							autoHideDuration={4000}
							// preventDuplicate
							variant="primary"
						>
							<Header />
							<ScrollToTopBtn />
							{children}
							<Footer />
						</SnackbarProvider>
					</StoreProvider>
				</body>
			{/* </CacheProvider> */}
		</html>
	);
};
export default RootLayout;
